### ISSUE TITLE
Docker image for dev environment

### ISSUE THREAD

**Issue by aiqc** [aiqc/aiqc#16]
> Difficulty: ★☆☆☆☆

## Background
AIQC has the following dependencies:
https://aiqc.readthedocs.io/en/latest/notebooks/installation.html 

- Specific version of Python for deep learning packages.
  - `setup.py`:`python_requires=''`
- User-facing Python package dependencies.
  - `setup.py`:`install_requires=[...]`
- Dev Python package dependencies (e.g. documentation).
  - `requirements_dev.txt`
- Executable documentation dependencies.
  - `brew install pandoc` on mac for building sphinx documentation html pages.
  - I also like to use `pyenv` and `virtualenv` for managing python version and envs.
- JupyterLab extension for visualization.
  - https://aiqc.readthedocs.io/en/latest/notebooks/installation.html#Plotting

## Problem
- We need a quick way to get collaborators up and running quickly.
- Not everyone uses the same OS.

## Solution
- A public Docker image hosted on Dockerhub.
- Push the Docker BUILD/ compose file to root of GitHub repo.

**Comment by adzuci** [comment]
Your example compose file is starting Jupyterlab, do you want that?

`docker-compose.yml`:
```
version: "3"
services:
  jupyter:
    image: "<jupyter lab image>"
    ports:
      - "8888:8888"
      - "80:80"
      - "443:443"
    volumes:
      - ~/docker:/home
    stdin_open: true
    tty: true
    command: jupyter lab --ip=0.0.0.0 --port=8888 --allow-root
```
`Dockerfile`:
```
FROM python:3.7

# node and npm = https://github.com/nodesource/distributions#debinstall
RUN curl -sL https://deb.nodesource.com/setup_13.x | bash -
RUN apt-get install -y nodejs
RUN apt-get install -y build-essential

# install jupyter, the extension, and rebuild
RUN pip install jupyterlab

# pip packages
COPY requirements.txt /
RUN pip install -r requirements.txt
RUN rm requirements.txt

WORKDIR /home
```

Do you want to be able to run one docker and/or docker-compose command to be able to open a fully provisioned notebook w/ `aiqc.setup()` and other things baked into the docker file(s) or would something like this be helpful on it's own?
```
# Distributed under the terms of <license>
FROM python:3.8-slim-buster

# Install AIQC
RUN pip install aiqc --upgrade --user
```

I also think it might make sense to create a https://hub.docker.com/u/aiqc user and drop those users credentials into a Github Secret so that a Github Action could publish a new version of the docker image every time a new PyPi release is cut, do you like that idea? (something like this, but hopefully not as complex: https://github.com/jupyter/docker-stacks/blob/master/.github/workflows/docker.yml#L26-L72)
